Feature/fixing annotations
RoyNyaga/rspec_tic_tac_toe pull request #3
Opened 2019-08-23 16:20 UTC by RoyNyaga

Created a test file each for every class as requested.

2019-08-24 04:25 UTC, bolah2009 requested changes
# Hi Team :wave: 

## Good job implementing the changes suggested in PR #2. :+1: 

### A few more required changes before a :+1:  :smile:

- Use [`let blocks`](https://github.com/rubocop-hq/rspec-style-guide#let-blocks) before, see comments below.
  > Instead of using before_each to define a variable for the test cases, use [let](https://github.com/rubocop-hq/rspec-style-guide#let-blocks).
- Add a README file
   > Remember about descriptive README file.

As this is a follow-up project from the **Tic-Tac-Toe (OOP)** project can you paste the link of the project on the readme and here too? :thinking: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-08-24 04:25 UTC, bolah2009 commented on spec/board_spec.rb
> +RSpec.describe Board do
#### `REQUIRED`

Consider using `let` instead, this file have 6 different place `board = Board.new` was defined. Using the below suggestion will avoid defining `board` in each example. Learn more [here](https://github.com/rubocop-hq/rspec-style-guide#let-blocks)

```suggestion
RSpec.describe Board do
  let(:board) { Board.new }
  
  describe ' #initialize_Board ' do
```

2019-08-24 04:25 UTC, bolah2009 commented on spec/board_spec.rb
> +      board = Board.new
#### `REQUIRED`

Following the above suggestion, this line is not needed anymore.

2019-08-24 04:25 UTC, bolah2009 commented on spec/board_spec.rb
> +      board = Board.new
#### `REQUIRED`

Following the above suggestion, this line is not needed anymore.

2019-08-24 04:25 UTC, bolah2009 commented on spec/board_spec.rb
> +      board = Board.new
#### `REQUIRED`

Following the above suggestion, this line is not needed anymore.

2019-08-24 04:25 UTC, bolah2009 commented on spec/board_spec.rb
> +      board = Board.new
#### `REQUIRED`

Following the above suggestion, this line is not needed anymore.

2019-08-24 04:25 UTC, bolah2009 commented on spec/board_spec.rb
> +      board = Board.new
#### `REQUIRED`

Following the above suggestion, this line is not needed anymore.

2019-08-24 04:25 UTC, bolah2009 commented on spec/board_spec.rb
> +      board = Board.new
#### `REQUIRED`

Following the above suggestion, this line is not needed anymore.

2019-08-25 05:03 UTC, RoyNyaga commented
Thanks for the review, we will get to work immediately


On Sat, Aug 24, 2019 at 5:25 AM BOLA AHMED BUARI <notifications@github.com>
wrote:

> *@bolah2009* requested changes on this pull request.
> Hi Team 👋
>
> Good job implementing the changes suggested in PR #1
> <https://github.com/RoyNyaga/rspec_tic_tac_toe/pull/1>. 👍
>
> Only one more required change on using let blocks
> <https://github.com/rubocop-hq/rspec-style-guide#let-blocks> before
> giving a 👍 see comments below 😄
>
> Good luck with your next submission. 🌟
>
> Cheers
> Bola <https://bolabuari.com/>
> ------------------------------
>
> In spec/board_spec.rb
> <https://github.com/RoyNyaga/rspec_tic_tac_toe/pull/3#discussion_r317344203>
> :
>
> > @@ -0,0 +1,68 @@
>
> +# frozen_string_literal: true
>
> +
>
> +require './lib/tic_tac_toe.rb'
>
> +
>
> +RSpec.describe Board do
>
>
> REQUIRED
>
> Consider using let instead, this file have 6 different place board =
> Board.new was defined. Using the below suggestion will avoid defining
> board in each example. Learn more here
> <https://github.com/rubocop-hq/rspec-style-guide#let-blocks>
> ⬇️ Suggested change
>
> -RSpec.describe Board do
>
> +RSpec.describe Board do
>
> +  let(:board) { Board.new }
>
> +
>
> +  describe ' #initialize_Board ' do
>
>
> ------------------------------
>
> In spec/board_spec.rb
> <https://github.com/RoyNyaga/rspec_tic_tac_toe/pull/3#discussion_r317344249>
> :
>
> > @@ -0,0 +1,68 @@
>
> +# frozen_string_literal: true
>
> +
>
> +require './lib/tic_tac_toe.rb'
>
> +
>
> +RSpec.describe Board do
>
> +  describe ' #initialize_Board ' do
>
> +    it ' test the correct number on each cell of the grid' do
>
> +      board = Board.new
>
>
> REQUIRED
>
> Following the above suggestion, this line is not needed anymore.
> ------------------------------
>
> In spec/board_spec.rb
> <https://github.com/RoyNyaga/rspec_tic_tac_toe/pull/3#discussion_r317344253>
> :
>
> > +  describe ' #initialize_Board ' do
>
> +    it ' test the correct number on each cell of the grid' do
>
> +      board = Board.new
>
> +      cond = true
>
> +      m_board = board.main_board.flatten
>
> +      m_board.each_with_index do |cell, index|
>
> +        cond = cell.to_i == (index + 1)
>
> +        break unless cond
>
> +      end
>
> +      expect(cond).to be true
>
> +    end
>
> +  end
>
> +
>
> +  describe '#check space' do
>
> +    it 'returns true when a space is availabe in the board' do
>
> +      board = Board.new
>
>
> REQUIRED
>
> Following the above suggestion, this line is not needed anymore.
> ------------------------------
>
> In spec/board_spec.rb
> <https://github.com/RoyNyaga/rspec_tic_tac_toe/pull/3#discussion_r317344256>
> :
>
> > +        cond = cell.to_i == (index + 1)
>
> +        break unless cond
>
> +      end
>
> +      expect(cond).to be true
>
> +    end
>
> +  end
>
> +
>
> +  describe '#check space' do
>
> +    it 'returns true when a space is availabe in the board' do
>
> +      board = Board.new
>
> +      cond = board.space?
>
> +      expect(cond).to be true
>
> +    end
>
> +
>
> +    it 'returns false when a space is not availabe in the board' do
>
> +      board = Board.new
>
>
> REQUIRED
>
> Following the above suggestion, this line is not needed anymore.
> ------------------------------
>
> In spec/board_spec.rb
> <https://github.com/RoyNyaga/rspec_tic_tac_toe/pull/3#discussion_r317344260>
> :
>
> > +      expect(cond).to be true
>
> +    end
>
> +
>
> +    it 'returns false when a space is not availabe in the board' do
>
> +      board = Board.new
>
> +      9.times do |n|
>
> +        board.save_choise_player('X', n + 1)
>
> +      end
>
> +      cond = board.space?
>
> +      expect(cond).to be false
>
> +    end
>
> +  end
>
> +
>
> +  describe ' #check_choise_player' do
>
> +    it ' when a player select a number of the empty grid ' do
>
> +      board = Board.new
>
>
> REQUIRED
>
> Following the above suggestion, this line is not needed anymore.
> ------------------------------
>
> In spec/board_spec.rb
> <https://github.com/RoyNyaga/rspec_tic_tac_toe/pull/3#discussion_r317344265>
> :
>
> > +      board = Board.new
>
> +      board.main_board[0][0] = 'X'
>
> +      board.main_board[0][1] = 'O'
>
> +      board.main_board[0][2] = 'X'
>
> +
>
> +      cond = board.check_choise_player(1) &&
>
> +             board.check_choise_player(2) &&
>
> +             board.check_choise_player(3)
>
> +
>
> +      expect(cond).to be false
>
> +    end
>
> +  end
>
> +
>
> +  describe ' #save_choise_player ' do
>
> +    it ' when a mark is saved in the grid of each Player selection' do
>
> +      board = Board.new
>
>
> REQUIRED
>
> Following the above suggestion, this line is not needed anymore.
> ------------------------------
>
> In spec/board_spec.rb
> <https://github.com/RoyNyaga/rspec_tic_tac_toe/pull/3#discussion_r317344266>
> :
>
> > +        board.save_choise_player('X', n + 1)
>
> +      end
>
> +      cond = board.space?
>
> +      expect(cond).to be false
>
> +    end
>
> +  end
>
> +
>
> +  describe ' #check_choise_player' do
>
> +    it ' when a player select a number of the empty grid ' do
>
> +      board = Board.new
>
> +      cond = board.check_choise_player(1) && board.check_choise_player(2)
>
> +      expect(cond).to be true
>
> +    end
>
> +
>
> +    it ' when a player select a number of the grid with saves' do
>
> +      board = Board.new
>
>
> REQUIRED
>
> Following the above suggestion, this line is not needed anymore.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/RoyNyaga/rspec_tic_tac_toe/pull/3?email_source=notifications&email_token=ALZGFHPKS5LLWYEV4JEZKE3QGCZ2DA5CNFSM4IPBIWR2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCCSWKUQ#pullrequestreview-279274834>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALZGFHLIICUJPWQBUJZJUZDQGCZ2DANCNFSM4IPBIWRQ>
> .
>

2019-08-26 22:15 UTC, Oghenebrume50 approved these changes
Good job guys this is fine, everything works now and perfectly implemented :smile:

2019-08-27 09:41 UTC, merged